### PR TITLE
feat: multiple XSD files from folder

### PR DESCRIPTION
**Pull request by biancode**
a bit refactoring and multiple XSD files via --schemes /path/of/xsdFiles or just a XSD file via --schema full_filename

### CODE REVIEW

**Comment by mristin** [comment]
@biancode thanks for the PR! I'll try to review it tomorrow (Friday 2020-11-20).

**Comment by mristin** [comment]
Could you maybe describe in more detail the feature and what the use case is?

**Comment by biancode** [comment]
if there is new a given path via --schemes /path/of/xsdFiles - then the program for XML loads all XSD files into the schema set - to reuse your first state of the code I did some refactoring to get validate and load XSD separated.

File XSD: 
`--schema C:/dev/github/AAS-Toolbox/xml/V2/AAS.xsd --inputs C:/dev/github/AAS-Toolbox/xml/V2/Example.xml`

Path XSDs:
`--schemes C:/dev/github/AAS-Toolbox/xml/V2/ --inputs C:/dev/github/AAS-Toolbox/xml/V2/Example.xml`

**Comment by biancode** [comment]
tested with https://github.com/BiancoRoyal/AAS-Toolbox files and folders

**Comment by biancode** [comment]
use case: AAS XML examples need three XSD to load and validate - AAS, AAS-ABAC, and IEC61360

**Comment by mristin** [comment]
@biancode thanks for the clarification! Are you sure that this change is needed? So far I could validate the files as long as the other two schemas were referenced from within the main XSD file.

Please have a look:
https://github.com/admin-shell-io/aas-specs/blob/master/schemas/Validate.ps1

This is how the other two schemas were referenced:
https://github.com/admin-shell-io/aas-specs/blob/master/schemas/xml/AAS.xsd#L3
https://github.com/admin-shell-io/aas-specs/blob/master/schemas/xml/AAS.xsd#L4

**Comment by biancode** [comment]
ok, then I have to check my XSD references in detail :)

**Comment by biancode** [comment]
should I close the PR?

**Comment by mristin** [comment]
Yes, let's close it for the moment. Please re-open if the XSD references do not work for you.

**Pull request closed without merging**
